const colors = require('../lib/colors.js')
const t = require('tap')

t.test('with colors', async t => {
  const c = colors(true)
  t.notEqual(c.green('x'), 'x')
  t.notEqual(c.red('x'), 'x')
  t.notEqual(c.magenta('x'), 'x')
  t.notEqual(c.yellow('x'), 'x')
  t.notEqual(c.white('x'), 'x')
  t.notEqual(c.dim('x'), 'x')
  t.equal(c.severity('low'), c.white('low'))
  t.equal(c.severity('MoDeRaTe'), c.yellow('MoDeRaTe'))
  t.equal(c.severity('hiGH'), c.red('hiGH'))
  t.equal(c.severity('crITicAL'), c.magenta('crITicAL'))
  t.equal(c.severity('low', 'x'), c.white('x'))
  t.equal(c.severity('MoDeRaTe', 'x'), c.yellow('x'))
  t.equal(c.severity('hiGH', 'x'), c.red('x'))
  t.equal(c.severity('crITicAL', 'x'), c.magenta('x'))
})

t.test('without colors', async t => {
  const c = colors(false)
  t.equal(c.green('x'), 'x')
  t.equal(c.red('x'), 'x')
  t.equal(c.magenta('x'), 'x')
  t.equal(c.yellow('x'), 'x')
  t.equal(c.white('x'), 'x')
  t.equal(c.dim('x'), 'x')
  t.equal(c.severity('low'), 'low')
  t.equal(c.severity('moderate'), 'moderate')
  t.equal(c.severity('high'), 'high')
  t.equal(c.severity('critical'), 'critical')
  t.equal(c.severity('low', 'x'), 'x')
  t.equal(c.severity('MoDeRaTe', 'x'), 'x')
  t.equal(c.severity('hiGH', 'x'), 'x')
  t.equal(c.severity('crITicAL', 'x'), 'x')
})
