const t = require('tap')
const chalk = require('./fixtures/chalk.js')
const colors = require('../lib/colors.js')

t.formatSnapshot = ({ report, exitCode }) => `${report}\nexitCode=${exitCode}`

t.test('with colors', async t => {
  const { color } = await chalk()
  const c = colors(color)
  t.not(c.green('x'), 'x')
  t.not(c.red('x'), 'x')
  t.not(c.magenta('x'), 'x')
  t.not(c.yellow('x'), 'x')
  t.not(c.white('x'), 'x')
  t.not(c.dim('x'), 'x')
  t.equal(c.severity('low'), c.white('low'))
  t.equal(c.severity('MoDeRaTe'), c.yellow('MoDeRaTe'))
  t.equal(c.severity('hiGH'), c.red('hiGH'))
  t.equal(c.severity('crITicAL'), c.magenta('crITicAL'))
  t.equal(c.severity('low', 'x'), c.white('x'))
  t.equal(c.severity('MoDeRaTe', 'x'), c.yellow('x'))
  t.equal(c.severity('hiGH', 'x'), c.red('x'))
  t.equal(c.severity('crITicAL', 'x'), c.magenta('x'))
})

t.test('without colors', async t => {
  const { noColor } = await chalk()
  const c = colors(noColor)
  t.equal(c.green('x'), 'x')
  t.equal(c.red('x'), 'x')
  t.equal(c.magenta('x'), 'x')
  t.equal(c.yellow('x'), 'x')
  t.equal(c.white('x'), 'x')
  t.equal(c.dim('x'), 'x')
  t.equal(c.severity('low'), 'low')
  t.equal(c.severity('moderate'), 'moderate')
  t.equal(c.severity('high'), 'high')
  t.equal(c.severity('critical'), 'critical')
  t.equal(c.severity('low', 'x'), 'x')
  t.equal(c.severity('MoDeRaTe', 'x'), 'x')
  t.equal(c.severity('hiGH', 'x'), 'x')
  t.equal(c.severity('crITicAL', 'x'), 'x')
})
